// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteRiskAssessmentIgnoredRisksIgnoredRiskIDRequest struct {
	IgnoredRiskID string `pathParam:"style=simple,explode=false,name=ignoredRiskId"`
}

func (o *DeleteRiskAssessmentIgnoredRisksIgnoredRiskIDRequest) GetIgnoredRiskID() string {
	if o == nil {
		return ""
	}
	return o.IgnoredRiskID
}

type DeleteRiskAssessmentIgnoredRisksIgnoredRiskIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteRiskAssessmentIgnoredRisksIgnoredRiskIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteRiskAssessmentIgnoredRisksIgnoredRiskIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteRiskAssessmentIgnoredRisksIgnoredRiskIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
