// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPISecurityOpenAPISpecsCatalogIDReconstructedSpecJSONRequest struct {
	CatalogID string `pathParam:"style=simple,explode=false,name=catalogId"`
	// When true, the API will return an json file, and pagination will be ignored
	DownloadAsJSON *bool `queryParam:"style=form,explode=true,name=downloadAsJson"`
}

func (o *GetAPISecurityOpenAPISpecsCatalogIDReconstructedSpecJSONRequest) GetCatalogID() string {
	if o == nil {
		return ""
	}
	return o.CatalogID
}

func (o *GetAPISecurityOpenAPISpecsCatalogIDReconstructedSpecJSONRequest) GetDownloadAsJSON() *bool {
	if o == nil {
		return nil
	}
	return o.DownloadAsJSON
}

type GetAPISecurityOpenAPISpecsCatalogIDReconstructedSpecJSONResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	String *string
}

func (o *GetAPISecurityOpenAPISpecsCatalogIDReconstructedSpecJSONResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPISecurityOpenAPISpecsCatalogIDReconstructedSpecJSONResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPISecurityOpenAPISpecsCatalogIDReconstructedSpecJSONResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPISecurityOpenAPISpecsCatalogIDReconstructedSpecJSONResponse) GetString() *string {
	if o == nil {
		return nil
	}
	return o.String
}
