// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type GetAdvisorClusterEventRulesResponse struct {
	// OK
	ClusterEventRuleRecommendationPeriods []shared.ClusterEventRuleRecommendationPeriod
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAdvisorClusterEventRulesResponse) GetClusterEventRuleRecommendationPeriods() []shared.ClusterEventRuleRecommendationPeriod {
	if o == nil {
		return nil
	}
	return o.ClusterEventRuleRecommendationPeriods
}

func (o *GetAdvisorClusterEventRulesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAdvisorClusterEventRulesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAdvisorClusterEventRulesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
