// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type GetAppsPolicySearchOptionsRequest struct {
	// the pod/env name to filter by.
	NameFilter *string `queryParam:"style=form,explode=true,name=nameFilter"`
}

func (o *GetAppsPolicySearchOptionsRequest) GetNameFilter() *string {
	if o == nil {
		return nil
	}
	return o.NameFilter
}

type GetAppsPolicySearchOptionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	PolicyFilterSearchResponse *shared.PolicyFilterSearchResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAppsPolicySearchOptionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAppsPolicySearchOptionsResponse) GetPolicyFilterSearchResponse() *shared.PolicyFilterSearchResponse {
	if o == nil {
		return nil
	}
	return o.PolicyFilterSearchResponse
}

func (o *GetAppsPolicySearchOptionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAppsPolicySearchOptionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
