// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAccountVulnerabilitiesXlsxRequest struct {
	// Filter images by HASH
	ImageHash []string `queryParam:"style=form,explode=false,name=IMAGE_HASH"`
	// Filter images by name
	ImageName []string `queryParam:"style=form,explode=false,name=IMAGE_NAME"`
	// Filter images by tags
	ImageTag []string `queryParam:"style=form,explode=false,name=IMAGE_TAG"`
	// Filter images by vulnerability name
	VulnerabilityName *string `queryParam:"style=form,explode=true,name=vulnerabilityName"`
}

func (o *GetAccountVulnerabilitiesXlsxRequest) GetImageHash() []string {
	if o == nil {
		return nil
	}
	return o.ImageHash
}

func (o *GetAccountVulnerabilitiesXlsxRequest) GetImageName() []string {
	if o == nil {
		return nil
	}
	return o.ImageName
}

func (o *GetAccountVulnerabilitiesXlsxRequest) GetImageTag() []string {
	if o == nil {
		return nil
	}
	return o.ImageTag
}

func (o *GetAccountVulnerabilitiesXlsxRequest) GetVulnerabilityName() *string {
	if o == nil {
		return nil
	}
	return o.VulnerabilityName
}

type GetAccountVulnerabilitiesXlsxResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAccountVulnerabilitiesXlsxResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAccountVulnerabilitiesXlsxResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAccountVulnerabilitiesXlsxResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
