// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type GetAppsPolicyRequest struct {
	// the filter to filter by. the string must be a json representation of PolicyFilter object
	PolicyFilter *string `queryParam:"style=form,explode=true,name=policyFilter"`
}

func (o *GetAppsPolicyRequest) GetPolicyFilter() *string {
	if o == nil {
		return nil
	}
	return o.PolicyFilter
}

type GetAppsPolicyResponse struct {
	// Success
	AppPolicy *shared.AppPolicy
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAppsPolicyResponse) GetAppPolicy() *shared.AppPolicy {
	if o == nil {
		return nil
	}
	return o.AppPolicy
}

func (o *GetAppsPolicyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAppsPolicyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAppsPolicyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
