// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/sdkerrors"
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type GetCloudAccountsCloudAccountIDDeleteDependenciesRequest struct {
	// cloud account ID
	CloudAccountID string `pathParam:"style=simple,explode=false,name=cloudAccountId"`
}

func (o *GetCloudAccountsCloudAccountIDDeleteDependenciesRequest) GetCloudAccountID() string {
	if o == nil {
		return ""
	}
	return o.CloudAccountID
}

type GetCloudAccountsCloudAccountIDDeleteDependenciesResponse struct {
	// unknown error
	APIResponse *sdkerrors.APIResponse
	// Success
	CloudAccountDeleteDependencies *shared.CloudAccountDeleteDependencies
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetCloudAccountsCloudAccountIDDeleteDependenciesResponse) GetAPIResponse() *sdkerrors.APIResponse {
	if o == nil {
		return nil
	}
	return o.APIResponse
}

func (o *GetCloudAccountsCloudAccountIDDeleteDependenciesResponse) GetCloudAccountDeleteDependencies() *shared.CloudAccountDeleteDependencies {
	if o == nil {
		return nil
	}
	return o.CloudAccountDeleteDependencies
}

func (o *GetCloudAccountsCloudAccountIDDeleteDependenciesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCloudAccountsCloudAccountIDDeleteDependenciesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCloudAccountsCloudAccountIDDeleteDependenciesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
