// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"github.com/speakeasy-sdks/testpan-go/pkg/utils"
	"net/http"
)

type GetDashboardTopSecurityRisksRequest struct {
	// the clusters ids to filter by
	ClustersIds []string `queryParam:"style=form,explode=true,name=clustersIds"`
	// Amount of top risky workloads to return
	Size *int64 `default:"5" queryParam:"style=form,explode=true,name=size"`
}

func (g GetDashboardTopSecurityRisksRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDashboardTopSecurityRisksRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetDashboardTopSecurityRisksRequest) GetClustersIds() []string {
	if o == nil {
		return nil
	}
	return o.ClustersIds
}

func (o *GetDashboardTopSecurityRisksRequest) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

type GetDashboardTopSecurityRisksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TopSecurityRisksWidget *shared.TopSecurityRisksWidget
}

func (o *GetDashboardTopSecurityRisksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetDashboardTopSecurityRisksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetDashboardTopSecurityRisksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetDashboardTopSecurityRisksResponse) GetTopSecurityRisksWidget() *shared.TopSecurityRisksWidget {
	if o == nil {
		return nil
	}
	return o.TopSecurityRisksWidget
}
