// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type GetEnvironmentsEnvIDRequest struct {
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
}

func (o *GetEnvironmentsEnvIDRequest) GetEnvID() string {
	if o == nil {
		return ""
	}
	return o.EnvID
}

type GetEnvironmentsEnvIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Classes []shared.Environment
}

func (o *GetEnvironmentsEnvIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetEnvironmentsEnvIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetEnvironmentsEnvIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetEnvironmentsEnvIDResponse) GetClasses() []shared.Environment {
	if o == nil {
		return nil
	}
	return o.Classes
}
