// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"github.com/speakeasy-sdks/testpan-go/pkg/utils"
	"net/http"
)

// GetGatewaysQueryParamSortDir - sorting direction
type GetGatewaysQueryParamSortDir string

const (
	GetGatewaysQueryParamSortDirAsc  GetGatewaysQueryParamSortDir = "ASC"
	GetGatewaysQueryParamSortDirDesc GetGatewaysQueryParamSortDir = "DESC"
)

func (e GetGatewaysQueryParamSortDir) ToPointer() *GetGatewaysQueryParamSortDir {
	return &e
}

func (e *GetGatewaysQueryParamSortDir) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ASC":
		fallthrough
	case "DESC":
		*e = GetGatewaysQueryParamSortDir(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetGatewaysQueryParamSortDir: %v", v)
	}
}

type GetGatewaysRequest struct {
	// The number of entries to return (pagination)
	MaxResults *float64 `default:"100" queryParam:"style=form,explode=true,name=maxResults"`
	// Filter gateways by name
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// When true, the pagination params will be ignored
	NoPagination *bool `queryParam:"style=form,explode=true,name=noPagination"`
	// Return entries from this offset (pagination)
	Offset *float64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// sorting direction
	SortDir *GetGatewaysQueryParamSortDir `default:"ASC" queryParam:"style=form,explode=true,name=sortDir"`
}

func (g GetGatewaysRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetGatewaysRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetGatewaysRequest) GetMaxResults() *float64 {
	if o == nil {
		return nil
	}
	return o.MaxResults
}

func (o *GetGatewaysRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetGatewaysRequest) GetNoPagination() *bool {
	if o == nil {
		return nil
	}
	return o.NoPagination
}

func (o *GetGatewaysRequest) GetOffset() *float64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetGatewaysRequest) GetSortDir() *GetGatewaysQueryParamSortDir {
	if o == nil {
		return nil
	}
	return o.SortDir
}

type GetGatewaysResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Classes []shared.Gateway
}

func (o *GetGatewaysResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetGatewaysResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetGatewaysResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetGatewaysResponse) GetClasses() []shared.Gateway {
	if o == nil {
		return nil
	}
	return o.Classes
}
