// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetIstioSupportedVersionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	GetIstioSupportedVersions200ApplicationJSONStrings []string
}

func (o *GetIstioSupportedVersionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetIstioSupportedVersionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetIstioSupportedVersionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetIstioSupportedVersionsResponse) GetGetIstioSupportedVersions200ApplicationJSONStrings() []string {
	if o == nil {
		return nil
	}
	return o.GetIstioSupportedVersions200ApplicationJSONStrings
}
