// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"github.com/speakeasy-sdks/testpan-go/pkg/utils"
	"net/http"
)

// GetImagesImageIDImageLayersQueryParamSortDir - sorting direction
type GetImagesImageIDImageLayersQueryParamSortDir string

const (
	GetImagesImageIDImageLayersQueryParamSortDirAsc  GetImagesImageIDImageLayersQueryParamSortDir = "ASC"
	GetImagesImageIDImageLayersQueryParamSortDirDesc GetImagesImageIDImageLayersQueryParamSortDir = "DESC"
)

func (e GetImagesImageIDImageLayersQueryParamSortDir) ToPointer() *GetImagesImageIDImageLayersQueryParamSortDir {
	return &e
}

func (e *GetImagesImageIDImageLayersQueryParamSortDir) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ASC":
		fallthrough
	case "DESC":
		*e = GetImagesImageIDImageLayersQueryParamSortDir(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetImagesImageIDImageLayersQueryParamSortDir: %v", v)
	}
}

type GetImagesImageIDImageLayersRequest struct {
	ImageID string `pathParam:"style=simple,explode=false,name=imageId"`
	// Return ignored / not ignored entries
	IsIgnored *bool `default:"false" queryParam:"style=form,explode=true,name=isIgnored"`
	// sorting direction
	SortDir *GetImagesImageIDImageLayersQueryParamSortDir `default:"ASC" queryParam:"style=form,explode=true,name=sortDir"`
}

func (g GetImagesImageIDImageLayersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetImagesImageIDImageLayersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetImagesImageIDImageLayersRequest) GetImageID() string {
	if o == nil {
		return ""
	}
	return o.ImageID
}

func (o *GetImagesImageIDImageLayersRequest) GetIsIgnored() *bool {
	if o == nil {
		return nil
	}
	return o.IsIgnored
}

func (o *GetImagesImageIDImageLayersRequest) GetSortDir() *GetImagesImageIDImageLayersQueryParamSortDir {
	if o == nil {
		return nil
	}
	return o.SortDir
}

type GetImagesImageIDImageLayersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ImageLayers *shared.ImageLayers
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetImagesImageIDImageLayersResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetImagesImageIDImageLayersResponse) GetImageLayers() *shared.ImageLayers {
	if o == nil {
		return nil
	}
	return o.ImageLayers
}

func (o *GetImagesImageIDImageLayersResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetImagesImageIDImageLayersResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
