// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type GetKubernetesAPIPolicyRecommendedRulesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	RecommendedKubernetesAPIRules []shared.RecommendedKubernetesAPIRule
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetKubernetesAPIPolicyRecommendedRulesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetKubernetesAPIPolicyRecommendedRulesResponse) GetRecommendedKubernetesAPIRules() []shared.RecommendedKubernetesAPIRule {
	if o == nil {
		return nil
	}
	return o.RecommendedKubernetesAPIRules
}

func (o *GetKubernetesAPIPolicyRecommendedRulesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetKubernetesAPIPolicyRecommendedRulesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
