// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"github.com/speakeasy-sdks/testpan-go/pkg/utils"
	"net/http"
)

// GetRiskAssessmentKubernetesClusterIDPodsSortDir - sorting direction
type GetRiskAssessmentKubernetesClusterIDPodsSortDir string

const (
	GetRiskAssessmentKubernetesClusterIDPodsSortDirAsc  GetRiskAssessmentKubernetesClusterIDPodsSortDir = "ASC"
	GetRiskAssessmentKubernetesClusterIDPodsSortDirDesc GetRiskAssessmentKubernetesClusterIDPodsSortDir = "DESC"
)

func (e GetRiskAssessmentKubernetesClusterIDPodsSortDir) ToPointer() *GetRiskAssessmentKubernetesClusterIDPodsSortDir {
	return &e
}

func (e *GetRiskAssessmentKubernetesClusterIDPodsSortDir) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ASC":
		fallthrough
	case "DESC":
		*e = GetRiskAssessmentKubernetesClusterIDPodsSortDir(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetRiskAssessmentKubernetesClusterIDPodsSortDir: %v", v)
	}
}

// GetRiskAssessmentKubernetesClusterIDPodsSortKey - risk assessment pod sort key.
type GetRiskAssessmentKubernetesClusterIDPodsSortKey string

const (
	GetRiskAssessmentKubernetesClusterIDPodsSortKeyName GetRiskAssessmentKubernetesClusterIDPodsSortKey = "NAME"
	GetRiskAssessmentKubernetesClusterIDPodsSortKeyRisk GetRiskAssessmentKubernetesClusterIDPodsSortKey = "RISK"
)

func (e GetRiskAssessmentKubernetesClusterIDPodsSortKey) ToPointer() *GetRiskAssessmentKubernetesClusterIDPodsSortKey {
	return &e
}

func (e *GetRiskAssessmentKubernetesClusterIDPodsSortKey) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NAME":
		fallthrough
	case "RISK":
		*e = GetRiskAssessmentKubernetesClusterIDPodsSortKey(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetRiskAssessmentKubernetesClusterIDPodsSortKey: %v", v)
	}
}

type GetRiskAssessmentKubernetesClusterIDPodsRequest struct {
	// When true, the API will return an xlsx file, and pagination will be ignored
	DownloadAsXlsx *bool `queryParam:"style=form,explode=true,name=downloadAsXlsx"`
	// Secure Application Kubernetes cluster ID
	KubernetesClusterID string `pathParam:"style=simple,explode=false,name=kubernetesClusterId"`
	// The number of entries to return (pagination)
	MaxResults *float64 `default:"100" queryParam:"style=form,explode=true,name=maxResults"`
	// namespace names filter. a base 64 representation of a list of namespace names definition object
	NamespacesNamesFilter *string `queryParam:"style=form,explode=true,name=namespacesNamesFilter"`
	// Return entries from this offset (pagination)
	Offset *float64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// sorting direction
	SortDir *GetRiskAssessmentKubernetesClusterIDPodsSortDir `default:"DESC" queryParam:"style=form,explode=true,name=sortDir"`
	// risk assessment pod sort key.
	SortKey GetRiskAssessmentKubernetesClusterIDPodsSortKey `default:"RISK" queryParam:"style=form,explode=true,name=sortKey"`
}

func (g GetRiskAssessmentKubernetesClusterIDPodsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRiskAssessmentKubernetesClusterIDPodsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsRequest) GetDownloadAsXlsx() *bool {
	if o == nil {
		return nil
	}
	return o.DownloadAsXlsx
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsRequest) GetKubernetesClusterID() string {
	if o == nil {
		return ""
	}
	return o.KubernetesClusterID
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsRequest) GetMaxResults() *float64 {
	if o == nil {
		return nil
	}
	return o.MaxResults
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsRequest) GetNamespacesNamesFilter() *string {
	if o == nil {
		return nil
	}
	return o.NamespacesNamesFilter
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsRequest) GetOffset() *float64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsRequest) GetSortDir() *GetRiskAssessmentKubernetesClusterIDPodsSortDir {
	if o == nil {
		return nil
	}
	return o.SortDir
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsRequest) GetSortKey() GetRiskAssessmentKubernetesClusterIDPodsSortKey {
	if o == nil {
		return GetRiskAssessmentKubernetesClusterIDPodsSortKey("")
	}
	return o.SortKey
}

type GetRiskAssessmentKubernetesClusterIDPodsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	RiskAssessmentPods []shared.RiskAssessmentPod
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsResponse) GetRiskAssessmentPods() []shared.RiskAssessmentPod {
	if o == nil {
		return nil
	}
	return o.RiskAssessmentPods
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRiskAssessmentKubernetesClusterIDPodsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
