// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type GetServerlessZipFilesZipIDRequest struct {
	ZipID string `pathParam:"style=simple,explode=false,name=zipId"`
}

func (o *GetServerlessZipFilesZipIDRequest) GetZipID() string {
	if o == nil {
		return ""
	}
	return o.ZipID
}

type GetServerlessZipFilesZipIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	ServerlessZip *shared.ServerlessZip
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetServerlessZipFilesZipIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetServerlessZipFilesZipIDResponse) GetServerlessZip() *shared.ServerlessZip {
	if o == nil {
		return nil
	}
	return o.ServerlessZip
}

func (o *GetServerlessZipFilesZipIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetServerlessZipFilesZipIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
