// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type PostAPISecurityInternalCatalogCatalogIDBflaLearningRequest struct {
	BflaDurationConfiguration shared.BflaDurationConfiguration `request:"mediaType=application/json"`
	CatalogID                 string                           `pathParam:"style=simple,explode=false,name=catalogId"`
}

func (o *PostAPISecurityInternalCatalogCatalogIDBflaLearningRequest) GetBflaDurationConfiguration() shared.BflaDurationConfiguration {
	if o == nil {
		return shared.BflaDurationConfiguration{}
	}
	return o.BflaDurationConfiguration
}

func (o *PostAPISecurityInternalCatalogCatalogIDBflaLearningRequest) GetCatalogID() string {
	if o == nil {
		return ""
	}
	return o.CatalogID
}

type PostAPISecurityInternalCatalogCatalogIDBflaLearningResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created
	Res *string
}

func (o *PostAPISecurityInternalCatalogCatalogIDBflaLearningResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAPISecurityInternalCatalogCatalogIDBflaLearningResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAPISecurityInternalCatalogCatalogIDBflaLearningResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostAPISecurityInternalCatalogCatalogIDBflaLearningResponse) GetRes() *string {
	if o == nil {
		return nil
	}
	return o.Res
}
