// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type PostLoginRequest struct {
	// google id token
	GoogleIDToken *string `header:"style=simple,explode=false,name=googleIdToken"`
	// cognito id token
	Token *string `header:"style=simple,explode=false,name=token"`
}

func (o *PostLoginRequest) GetGoogleIDToken() *string {
	if o == nil {
		return nil
	}
	return o.GoogleIDToken
}

func (o *PostLoginRequest) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

type PostLoginResponse struct {
	// Accepted. Challenge required
	ChallengeRequest *shared.ChallengeRequest
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	UserLoginInfo *shared.UserLoginInfo
}

func (o *PostLoginResponse) GetChallengeRequest() *shared.ChallengeRequest {
	if o == nil {
		return nil
	}
	return o.ChallengeRequest
}

func (o *PostLoginResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostLoginResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostLoginResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostLoginResponse) GetUserLoginInfo() *shared.UserLoginInfo {
	if o == nil {
		return nil
	}
	return o.UserLoginInfo
}
