// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type PostAgentsAgentIDUpdateRequest struct {
	// Secure Application agent ID
	AgentID string `pathParam:"style=simple,explode=false,name=agentId"`
}

func (o *PostAgentsAgentIDUpdateRequest) GetAgentID() string {
	if o == nil {
		return ""
	}
	return o.AgentID
}

type PostAgentsAgentIDUpdateResponse struct {
	// Account is disabled.
	APIResponse *shared.APIResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostAgentsAgentIDUpdateResponse) GetAPIResponse() *shared.APIResponse {
	if o == nil {
		return nil
	}
	return o.APIResponse
}

func (o *PostAgentsAgentIDUpdateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAgentsAgentIDUpdateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAgentsAgentIDUpdateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
