// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type PutAPISecurityOpenAPISpecsCatalogIDRequest struct {
	RequestBody string `request:"mediaType=application/json"`
	CatalogID   string `pathParam:"style=simple,explode=false,name=catalogId"`
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDRequest) GetRequestBody() string {
	if o == nil {
		return ""
	}
	return o.RequestBody
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDRequest) GetCatalogID() string {
	if o == nil {
		return ""
	}
	return o.CatalogID
}

type PutAPISecurityOpenAPISpecsCatalogIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	OpenAPISpec *shared.OpenAPISpec
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDResponse) GetOpenAPISpec() *shared.OpenAPISpec {
	if o == nil {
		return nil
	}
	return o.OpenAPISpec
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
