// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type PutPodSecurityPolicyProfilesProfileIDRequest struct {
	PodSecurityPolicy shared.PodSecurityPolicy `request:"mediaType=application/json"`
	ProfileID         string                   `pathParam:"style=simple,explode=false,name=profileId"`
}

func (o *PutPodSecurityPolicyProfilesProfileIDRequest) GetPodSecurityPolicy() shared.PodSecurityPolicy {
	if o == nil {
		return shared.PodSecurityPolicy{}
	}
	return o.PodSecurityPolicy
}

func (o *PutPodSecurityPolicyProfilesProfileIDRequest) GetProfileID() string {
	if o == nil {
		return ""
	}
	return o.ProfileID
}

type PutPodSecurityPolicyProfilesProfileIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	PodSecurityPolicy *shared.PodSecurityPolicy
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutPodSecurityPolicyProfilesProfileIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutPodSecurityPolicyProfilesProfileIDResponse) GetPodSecurityPolicy() *shared.PodSecurityPolicy {
	if o == nil {
		return nil
	}
	return o.PodSecurityPolicy
}

func (o *PutPodSecurityPolicyProfilesProfileIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutPodSecurityPolicyProfilesProfileIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
