// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/models/shared"
	"net/http"
)

type PutTokensTokenIDRequest struct {
	Token   shared.Token `request:"mediaType=application/json"`
	TokenID string       `pathParam:"style=simple,explode=false,name=tokenId"`
}

func (o *PutTokensTokenIDRequest) GetToken() shared.Token {
	if o == nil {
		return shared.Token{}
	}
	return o.Token
}

func (o *PutTokensTokenIDRequest) GetTokenID() string {
	if o == nil {
		return ""
	}
	return o.TokenID
}

type PutTokensTokenIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Token was edited.
	Token *shared.Token
}

func (o *PutTokensTokenIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutTokensTokenIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutTokensTokenIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PutTokensTokenIDResponse) GetToken() *shared.Token {
	if o == nil {
		return nil
	}
	return o.Token
}
