// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AccountTier - K8s security product tier
type AccountTier string

const (
	AccountTierReveal  AccountTier = "REVEAL"
	AccountTierConnect AccountTier = "CONNECT"
	AccountTierTrial   AccountTier = "TRIAL"
	AccountTierPro     AccountTier = "PRO"
)

func (e AccountTier) ToPointer() *AccountTier {
	return &e
}

func (e *AccountTier) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "REVEAL":
		fallthrough
	case "CONNECT":
		fallthrough
	case "TRIAL":
		fallthrough
	case "PRO":
		*e = AccountTier(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountTier: %v", v)
	}
}
