// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type AgentGatherInformationState string

const (
	AgentGatherInformationStateNew        AgentGatherInformationState = "NEW"
	AgentGatherInformationStateProcessing AgentGatherInformationState = "PROCESSING"
	AgentGatherInformationStateDone       AgentGatherInformationState = "DONE"
	AgentGatherInformationStateFailed     AgentGatherInformationState = "FAILED"
	AgentGatherInformationStateNone       AgentGatherInformationState = "NONE"
)

func (e AgentGatherInformationState) ToPointer() *AgentGatherInformationState {
	return &e
}

func (e *AgentGatherInformationState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NEW":
		fallthrough
	case "PROCESSING":
		fallthrough
	case "DONE":
		fallthrough
	case "FAILED":
		fallthrough
	case "NONE":
		*e = AgentGatherInformationState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentGatherInformationState: %v", v)
	}
}

type Agent struct {
	Environments           []AgentEnvironment           `json:"environments,omitempty"`
	GatherInformationState *AgentGatherInformationState `json:"gatherInformationState,omitempty"`
	// sha2 of the content of the public key pem. The fingerprint format is xx:xx:xx...
	ID                *string        `json:"id,omitempty"`
	Info              *AgentInfo     `json:"info,omitempty"`
	Instance          *AgentInstance `json:"instance,omitempty"`
	IsUpdateEnabled   *bool          `json:"isUpdateEnabled,omitempty"`
	KubernetesVersion *string        `json:"kubernetesVersion,omitempty"`
	Nodes             *int64         `json:"nodes,omitempty"`
	SharedSecret      *string        `json:"sharedSecret,omitempty"`
	StatusCodes       []string       `json:"statusCodes,omitempty"`
	// The type of agent. Possible values are instance agent or k8s agent.
	Type  *AgentType `json:"type,omitempty"`
	Vcpus *string    `json:"vcpus,omitempty"`
}

func (o *Agent) GetEnvironments() []AgentEnvironment {
	if o == nil {
		return nil
	}
	return o.Environments
}

func (o *Agent) GetGatherInformationState() *AgentGatherInformationState {
	if o == nil {
		return nil
	}
	return o.GatherInformationState
}

func (o *Agent) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Agent) GetInfo() *AgentInfo {
	if o == nil {
		return nil
	}
	return o.Info
}

func (o *Agent) GetInstance() *AgentInstance {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *Agent) GetIsUpdateEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.IsUpdateEnabled
}

func (o *Agent) GetKubernetesVersion() *string {
	if o == nil {
		return nil
	}
	return o.KubernetesVersion
}

func (o *Agent) GetNodes() *int64 {
	if o == nil {
		return nil
	}
	return o.Nodes
}

func (o *Agent) GetSharedSecret() *string {
	if o == nil {
		return nil
	}
	return o.SharedSecret
}

func (o *Agent) GetStatusCodes() []string {
	if o == nil {
		return nil
	}
	return o.StatusCodes
}

func (o *Agent) GetType() *AgentType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Agent) GetVcpus() *string {
	if o == nil {
		return nil
	}
	return o.Vcpus
}
