// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AllowedHostPath struct {
	PathPrefix *string `json:"pathPrefix,omitempty"`
	ReadOnly   *bool   `json:"readOnly,omitempty"`
}

func (o *AllowedHostPath) GetPathPrefix() *string {
	if o == nil {
		return nil
	}
	return o.PathPrefix
}

func (o *AllowedHostPath) GetReadOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ReadOnly
}
