// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APIReconstructionRequest struct {
	ClusterID        *string `json:"clusterId,omitempty"`
	LearningDuration *string `json:"learningDuration,omitempty"`
}

func (o *APIReconstructionRequest) GetClusterID() *string {
	if o == nil {
		return nil
	}
	return o.ClusterID
}

func (o *APIReconstructionRequest) GetLearningDuration() *string {
	if o == nil {
		return nil
	}
	return o.LearningDuration
}
