// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APISecRiskFindingsWidget struct {
	Critical    *int64 `json:"critical,omitempty"`
	High        *int64 `json:"high,omitempty"`
	Low         *int64 `json:"low,omitempty"`
	Medium      *int64 `json:"medium,omitempty"`
	NoKnownRisk *int64 `json:"noKnownRisk,omitempty"`
	Total       *int64 `json:"total,omitempty"`
}

func (o *APISecRiskFindingsWidget) GetCritical() *int64 {
	if o == nil {
		return nil
	}
	return o.Critical
}

func (o *APISecRiskFindingsWidget) GetHigh() *int64 {
	if o == nil {
		return nil
	}
	return o.High
}

func (o *APISecRiskFindingsWidget) GetLow() *int64 {
	if o == nil {
		return nil
	}
	return o.Low
}

func (o *APISecRiskFindingsWidget) GetMedium() *int64 {
	if o == nil {
		return nil
	}
	return o.Medium
}

func (o *APISecRiskFindingsWidget) GetNoKnownRisk() *int64 {
	if o == nil {
		return nil
	}
	return o.NoKnownRisk
}

func (o *APISecRiskFindingsWidget) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}
