// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APISecurityPolicyCategoryCondition struct {
	Category                string                        `json:"category"`
	HighestAcceptedSeverity APISecurityPolicyRiskSeverity `json:"highestAcceptedSeverity"`
}

func (o *APISecurityPolicyCategoryCondition) GetCategory() string {
	if o == nil {
		return ""
	}
	return o.Category
}

func (o *APISecurityPolicyCategoryCondition) GetHighestAcceptedSeverity() APISecurityPolicyRiskSeverity {
	if o == nil {
		return APISecurityPolicyRiskSeverity("")
	}
	return o.HighestAcceptedSeverity
}
