// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APISecTopRiskyFinding struct {
	Category string          `json:"category"`
	ID       *string         `json:"id,omitempty"`
	Name     string          `json:"name"`
	Risk     APISecurityRisk `json:"risk"`
}

func (o *APISecTopRiskyFinding) GetCategory() string {
	if o == nil {
		return ""
	}
	return o.Category
}

func (o *APISecTopRiskyFinding) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *APISecTopRiskyFinding) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *APISecTopRiskyFinding) GetRisk() APISecurityRisk {
	if o == nil {
		return APISecurityRisk("")
	}
	return o.Risk
}
