// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APISecTopRiskyFindingsWidget struct {
	Findings []APISecTopRiskyFinding `json:"findings,omitempty"`
}

func (o *APISecTopRiskyFindingsWidget) GetFindings() []APISecTopRiskyFinding {
	if o == nil {
		return nil
	}
	return o.Findings
}
