// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/utils"
	"time"
)

type APIServiceBflaInfo struct {
	EndTime *time.Time               `json:"endTime,omitempty"`
	Status  APIServiceBflaInfoStatus `json:"status"`
	Tags    []APIServiceBflaTagInfo  `json:"tags,omitempty"`
}

func (a APIServiceBflaInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIServiceBflaInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *APIServiceBflaInfo) GetEndTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *APIServiceBflaInfo) GetStatus() APIServiceBflaInfoStatus {
	if o == nil {
		return APIServiceBflaInfoStatus("")
	}
	return o.Status
}

func (o *APIServiceBflaInfo) GetTags() []APIServiceBflaTagInfo {
	if o == nil {
		return nil
	}
	return o.Tags
}
