// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APIServiceTags struct {
	Names []string `json:"names"`
}

func (o *APIServiceTags) GetNames() []string {
	if o == nil {
		return []string{}
	}
	return o.Names
}
