// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APISecTopRiskyAPI struct {
	ID   *string `json:"id,omitempty"`
	Name string  `json:"name"`
	// An `enum`eration.
	Type APIServiceType `json:"type"`
	// Vulnerabilities summary by severity
	VulnerabilitiesSummary *VulnerabilitiesSummary `json:"vulnerabilitiesSummary,omitempty"`
}

func (o *APISecTopRiskyAPI) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *APISecTopRiskyAPI) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *APISecTopRiskyAPI) GetType() APIServiceType {
	if o == nil {
		return APIServiceType("")
	}
	return o.Type
}

func (o *APISecTopRiskyAPI) GetVulnerabilitiesSummary() *VulnerabilitiesSummary {
	if o == nil {
		return nil
	}
	return o.VulnerabilitiesSummary
}
