// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CDDeploymentResource struct {
	Reasons      []string               `json:"reasons,omitempty"`
	ResourceName *string                `json:"resourceName,omitempty"`
	Risk         *CDPipelineFindingRisk `json:"risk,omitempty"`
	Type         *CDPipelineFindingType `json:"type,omitempty"`
}

func (o *CDDeploymentResource) GetReasons() []string {
	if o == nil {
		return nil
	}
	return o.Reasons
}

func (o *CDDeploymentResource) GetResourceName() *string {
	if o == nil {
		return nil
	}
	return o.ResourceName
}

func (o *CDDeploymentResource) GetRisk() *CDPipelineFindingRisk {
	if o == nil {
		return nil
	}
	return o.Risk
}

func (o *CDDeploymentResource) GetType() *CDPipelineFindingType {
	if o == nil {
		return nil
	}
	return o.Type
}
