// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CDPipelineSecurityFindingValue struct {
	Count *int64                 `json:"count,omitempty"`
	Risk  *CDPipelineFindingRisk `json:"risk,omitempty"`
}

func (o *CDPipelineSecurityFindingValue) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CDPipelineSecurityFindingValue) GetRisk() *CDPipelineFindingRisk {
	if o == nil {
		return nil
	}
	return o.Risk
}
