// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/utils"
	"time"
)

// CDPipelineResult - Pipeline result for a scanned CD resource
type CDPipelineResult struct {
	DeploymentName    *string                     `json:"deploymentName,omitempty"`
	DeploymentSource  *DeploymentSource           `json:"deploymentSource,omitempty"`
	DeploymentVersion *string                     `json:"deploymentVersion,omitempty"`
	ID                *string                     `json:"id,omitempty"`
	PolicyID          *string                     `json:"policyId,omitempty"`
	PolicyName        *string                     `json:"policyName,omitempty"`
	Result            *CDResult                   `json:"result,omitempty"`
	SecurityFinding   []CDPipelineSecurityFinding `json:"securityFinding,omitempty"`
	Status            *CDPipelineResultStatus     `json:"status,omitempty"`
	Time              *time.Time                  `json:"time,omitempty"`
}

func (c CDPipelineResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CDPipelineResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CDPipelineResult) GetDeploymentName() *string {
	if o == nil {
		return nil
	}
	return o.DeploymentName
}

func (o *CDPipelineResult) GetDeploymentSource() *DeploymentSource {
	if o == nil {
		return nil
	}
	return o.DeploymentSource
}

func (o *CDPipelineResult) GetDeploymentVersion() *string {
	if o == nil {
		return nil
	}
	return o.DeploymentVersion
}

func (o *CDPipelineResult) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CDPipelineResult) GetPolicyID() *string {
	if o == nil {
		return nil
	}
	return o.PolicyID
}

func (o *CDPipelineResult) GetPolicyName() *string {
	if o == nil {
		return nil
	}
	return o.PolicyName
}

func (o *CDPipelineResult) GetResult() *CDResult {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *CDPipelineResult) GetSecurityFinding() []CDPipelineSecurityFinding {
	if o == nil {
		return nil
	}
	return o.SecurityFinding
}

func (o *CDPipelineResult) GetStatus() *CDPipelineResultStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CDPipelineResult) GetTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.Time
}
