// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CDPipelineSecurityFinding struct {
	Type  *CDPipelineFindingType          `json:"type,omitempty"`
	Value *CDPipelineSecurityFindingValue `json:"value,omitempty"`
}

func (o *CDPipelineSecurityFinding) GetType() *CDPipelineFindingType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *CDPipelineSecurityFinding) GetValue() *CDPipelineSecurityFindingValue {
	if o == nil {
		return nil
	}
	return o.Value
}
