// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CdPolicyElement struct {
	EnforcementOption             EnforcementOption     `json:"enforcementOption"`
	PermissibleVulnerabilityLevel CDPipelineFindingRisk `json:"permissibleVulnerabilityLevel"`
}

func (o *CdPolicyElement) GetEnforcementOption() EnforcementOption {
	if o == nil {
		return EnforcementOption("")
	}
	return o.EnforcementOption
}

func (o *CdPolicyElement) GetPermissibleVulnerabilityLevel() CDPipelineFindingRisk {
	if o == nil {
		return CDPipelineFindingRisk("")
	}
	return o.PermissibleVulnerabilityLevel
}
