// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ClusterDetails struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (o *ClusterDetails) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ClusterDetails) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
