// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CvssInfo struct {
	Score   float32 `json:"score"`
	Source  string  `json:"source"`
	Type    string  `json:"type"`
	Vector  string  `json:"vector"`
	Version string  `json:"version"`
}

func (o *CvssInfo) GetScore() float32 {
	if o == nil {
		return 0.0
	}
	return o.Score
}

func (o *CvssInfo) GetSource() string {
	if o == nil {
		return ""
	}
	return o.Source
}

func (o *CvssInfo) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *CvssInfo) GetVector() string {
	if o == nil {
		return ""
	}
	return o.Vector
}

func (o *CvssInfo) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}
