// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DashboardTimeBasedGraphs struct {
	LastDay   *DashboardTimeBasedGraph `json:"lastDay,omitempty"`
	LastHour  *DashboardTimeBasedGraph `json:"lastHour,omitempty"`
	LastMonth *DashboardTimeBasedGraph `json:"lastMonth,omitempty"`
	LastWeek  *DashboardTimeBasedGraph `json:"lastWeek,omitempty"`
}

func (o *DashboardTimeBasedGraphs) GetLastDay() *DashboardTimeBasedGraph {
	if o == nil {
		return nil
	}
	return o.LastDay
}

func (o *DashboardTimeBasedGraphs) GetLastHour() *DashboardTimeBasedGraph {
	if o == nil {
		return nil
	}
	return o.LastHour
}

func (o *DashboardTimeBasedGraphs) GetLastMonth() *DashboardTimeBasedGraph {
	if o == nil {
		return nil
	}
	return o.LastMonth
}

func (o *DashboardTimeBasedGraphs) GetLastWeek() *DashboardTimeBasedGraph {
	if o == nil {
		return nil
	}
	return o.LastWeek
}
