// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Type string

const (
	TypeAllowAll        Type = "ALLOW_ALL"
	TypeEnvironmentOnly Type = "ENVIRONMENT_ONLY"
	TypeDenyAll         Type = "DENY_ALL"
)

func (e Type) ToPointer() *Type {
	return &e
}

func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ALLOW_ALL":
		fallthrough
	case "ENVIRONMENT_ONLY":
		fallthrough
	case "DENY_ALL":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type DefaultConnectionRule struct {
	// ENCRYPT is not allowed in default rule
	Action *ConnectionRuleAction `json:"action,omitempty"`
	Type   *Type                 `json:"type,omitempty"`
}

func (o *DefaultConnectionRule) GetAction() *ConnectionRuleAction {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *DefaultConnectionRule) GetType() *Type {
	if o == nil {
		return nil
	}
	return o.Type
}
