// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DockerfileScanResult struct {
	Description *string                 `json:"description,omitempty"`
	ID          *string                 `json:"id,omitempty"`
	Name        *string                 `json:"name,omitempty"`
	Severity    *DockerfileScanSeverity `json:"severity,omitempty"`
	Title       *string                 `json:"title,omitempty"`
}

func (o *DockerfileScanResult) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *DockerfileScanResult) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *DockerfileScanResult) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *DockerfileScanResult) GetSeverity() *DockerfileScanSeverity {
	if o == nil {
		return nil
	}
	return o.Severity
}

func (o *DockerfileScanResult) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}
