// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type EncryptionReason string

const (
	EncryptionReasonPolicy          EncryptionReason = "POLICY"
	EncryptionReasonClusterOutbound EncryptionReason = "CLUSTER_OUTBOUND"
)

func (e EncryptionReason) ToPointer() *EncryptionReason {
	return &e
}

func (e *EncryptionReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "POLICY":
		fallthrough
	case "CLUSTER_OUTBOUND":
		*e = EncryptionReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EncryptionReason: %v", v)
	}
}
