// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EnvironmentRulesRecommendationPeriod struct {
	EnvironmentRulesRecommendations []EnvironmentRuleRecommendation `json:"environmentRulesRecommendations,omitempty"`
	TimePeriod                      *RecommendationTimePeriod       `json:"timePeriod,omitempty"`
	TotalWorkloads                  *int64                          `json:"totalWorkloads,omitempty"`
}

func (o *EnvironmentRulesRecommendationPeriod) GetEnvironmentRulesRecommendations() []EnvironmentRuleRecommendation {
	if o == nil {
		return nil
	}
	return o.EnvironmentRulesRecommendations
}

func (o *EnvironmentRulesRecommendationPeriod) GetTimePeriod() *RecommendationTimePeriod {
	if o == nil {
		return nil
	}
	return o.TimePeriod
}

func (o *EnvironmentRulesRecommendationPeriod) GetTotalWorkloads() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalWorkloads
}
