// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EventsForwardingDetailsList struct {
	Details []EventsForwardingDetails `json:"details,omitempty"`
}

func (o *EventsForwardingDetailsList) GetDetails() []EventsForwardingDetails {
	if o == nil {
		return nil
	}
	return o.Details
}
