// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type EventsForwardingDetailsTypeEnum string

const (
	EventsForwardingDetailsTypeEnumSplunkEventsForwardingDetails                 EventsForwardingDetailsTypeEnum = "SplunkEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumOpsGenieEventsForwardingDetails               EventsForwardingDetailsTypeEnum = "OpsGenieEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumSlackEventsForwardingDetails                  EventsForwardingDetailsTypeEnum = "SlackEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumSlackVulnerabilityEventsForwardingDetails     EventsForwardingDetailsTypeEnum = "SlackVulnerabilityEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumSumoLogicEventsForwardingDetails              EventsForwardingDetailsTypeEnum = "SumoLogicEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumSumoLogicVulnerabilityEventsForwardingDetails EventsForwardingDetailsTypeEnum = "SumoLogicVulnerabilityEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumWebexEventsForwardingDetails                  EventsForwardingDetailsTypeEnum = "WebexEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumWebexVulnerabilityEventsForwardingDetails     EventsForwardingDetailsTypeEnum = "WebexVulnerabilityEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumSecureXEventsForwardingDetails                EventsForwardingDetailsTypeEnum = "SecureXEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumSecureXVulnerabilityEventsForwardingDetails   EventsForwardingDetailsTypeEnum = "SecureXVulnerabilityEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumTeamsEventsForwardingDetails                  EventsForwardingDetailsTypeEnum = "TeamsEventsForwardingDetails"
	EventsForwardingDetailsTypeEnumTeamsVulnerabilityEventsForwardingDetails     EventsForwardingDetailsTypeEnum = "TeamsVulnerabilityEventsForwardingDetails"
)

func (e EventsForwardingDetailsTypeEnum) ToPointer() *EventsForwardingDetailsTypeEnum {
	return &e
}

func (e *EventsForwardingDetailsTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SplunkEventsForwardingDetails":
		fallthrough
	case "OpsGenieEventsForwardingDetails":
		fallthrough
	case "SlackEventsForwardingDetails":
		fallthrough
	case "SlackVulnerabilityEventsForwardingDetails":
		fallthrough
	case "SumoLogicEventsForwardingDetails":
		fallthrough
	case "SumoLogicVulnerabilityEventsForwardingDetails":
		fallthrough
	case "WebexEventsForwardingDetails":
		fallthrough
	case "WebexVulnerabilityEventsForwardingDetails":
		fallthrough
	case "SecureXEventsForwardingDetails":
		fallthrough
	case "SecureXVulnerabilityEventsForwardingDetails":
		fallthrough
	case "TeamsEventsForwardingDetails":
		fallthrough
	case "TeamsVulnerabilityEventsForwardingDetails":
		*e = EventsForwardingDetailsTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EventsForwardingDetailsTypeEnum: %v", v)
	}
}
