// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ImageLayer - image layer
type ImageLayer struct {
	Command         *string         `json:"command,omitempty"`
	ID              *string         `json:"id,omitempty"`
	Vulnerabilities []Vulnerability `json:"vulnerabilities,omitempty"`
}

func (o *ImageLayer) GetCommand() *string {
	if o == nil {
		return nil
	}
	return o.Command
}

func (o *ImageLayer) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ImageLayer) GetVulnerabilities() []Vulnerability {
	if o == nil {
		return nil
	}
	return o.Vulnerabilities
}
