// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/testpan-go/pkg/utils"
	"time"
)

// ImageDefInput - Authorized image hash
type ImageDefInput struct {
	// Valid hash for the image. * will authorize image name without validating hash
	ImageHash *string    `json:"imageHash,omitempty"`
	ImageName *string    `json:"imageName,omitempty"`
	ImageTags []string   `json:"imageTags,omitempty"`
	TimeAdded *time.Time `json:"timeAdded,omitempty"`
}

func (i ImageDefInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageDefInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ImageDefInput) GetImageHash() *string {
	if o == nil {
		return nil
	}
	return o.ImageHash
}

func (o *ImageDefInput) GetImageName() *string {
	if o == nil {
		return nil
	}
	return o.ImageName
}

func (o *ImageDefInput) GetImageTags() []string {
	if o == nil {
		return nil
	}
	return o.ImageTags
}

func (o *ImageDefInput) GetTimeAdded() *time.Time {
	if o == nil {
		return nil
	}
	return o.TimeAdded
}
