// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ImageSbomPathResponse struct {
	SbomPath *string `json:"sbomPath,omitempty"`
}

func (o *ImageSbomPathResponse) GetSbomPath() *string {
	if o == nil {
		return nil
	}
	return o.SbomPath
}
