// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MitreDashboardNamespace struct {
	IsCompromised *bool   `json:"isCompromised,omitempty"`
	Name          *string `json:"name,omitempty"`
}

func (o *MitreDashboardNamespace) GetIsCompromised() *bool {
	if o == nil {
		return nil
	}
	return o.IsCompromised
}

func (o *MitreDashboardNamespace) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
