// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OpenAPISpecScoreStatus string

const (
	OpenAPISpecScoreStatusScored    OpenAPISpecScoreStatus = "SCORED"
	OpenAPISpecScoreStatusNotScored OpenAPISpecScoreStatus = "NOT_SCORED"
)

func (e OpenAPISpecScoreStatus) ToPointer() *OpenAPISpecScoreStatus {
	return &e
}

func (e *OpenAPISpecScoreStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SCORED":
		fallthrough
	case "NOT_SCORED":
		*e = OpenAPISpecScoreStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenAPISpecScoreStatus: %v", v)
	}
}
