// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PolicyFilterSearchResponsePod struct {
	Labels []Label `json:"labels,omitempty"`
	Name   *string `json:"name,omitempty"`
}

func (o *PolicyFilterSearchResponsePod) GetLabels() []Label {
	if o == nil {
		return nil
	}
	return o.Labels
}

func (o *PolicyFilterSearchResponsePod) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
