// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RecommendedKubernetesAPIRule struct {
	Description        *string `json:"description,omitempty"`
	ID                 *string `json:"id,omitempty"`
	IsClusterScopeOnly *bool   `json:"isClusterScopeOnly,omitempty"`
	Name               *string `json:"name,omitempty"`
}

func (o *RecommendedKubernetesAPIRule) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *RecommendedKubernetesAPIRule) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RecommendedKubernetesAPIRule) GetIsClusterScopeOnly() *bool {
	if o == nil {
		return nil
	}
	return o.IsClusterScopeOnly
}

func (o *RecommendedKubernetesAPIRule) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
