// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// RiskTrendEnum - An enumeration.
type RiskTrendEnum string

const (
	RiskTrendEnumImproving RiskTrendEnum = "IMPROVING"
	RiskTrendEnumStable    RiskTrendEnum = "STABLE"
	RiskTrendEnumDegrading RiskTrendEnum = "DEGRADING"
)

func (e RiskTrendEnum) ToPointer() *RiskTrendEnum {
	return &e
}

func (e *RiskTrendEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "IMPROVING":
		fallthrough
	case "STABLE":
		fallthrough
	case "DEGRADING":
		*e = RiskTrendEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RiskTrendEnum: %v", v)
	}
}
