// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type RiskAssessmentScanFailureType string

const (
	RiskAssessmentScanFailureTypeDockerfileScan      RiskAssessmentScanFailureType = "DOCKERFILE_SCAN"
	RiskAssessmentScanFailureTypeVulnerabilitiesScan RiskAssessmentScanFailureType = "VULNERABILITIES_SCAN"
	RiskAssessmentScanFailureTypeInitializeScan      RiskAssessmentScanFailureType = "INITIALIZE_SCAN"
)

func (e RiskAssessmentScanFailureType) ToPointer() *RiskAssessmentScanFailureType {
	return &e
}

func (e *RiskAssessmentScanFailureType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DOCKERFILE_SCAN":
		fallthrough
	case "VULNERABILITIES_SCAN":
		fallthrough
	case "INITIALIZE_SCAN":
		*e = RiskAssessmentScanFailureType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RiskAssessmentScanFailureType: %v", v)
	}
}
