// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Role - The role of the user
type Role string

const (
	RoleLightspinAdmin   Role = "LIGHTSPIN_ADMIN"
	RoleCiscoSubscriber  Role = "CISCO_SUBSCRIBER"
	RoleSelfProvisioning Role = "SELF_PROVISIONING"
	RoleCiCdScanner      Role = "CI_CD_SCANNER"
	RolePortshiftAdmin   Role = "PORTSHIFT_ADMIN"
	RolePortshiftAuditor Role = "PORTSHIFT_AUDITOR"
	RoleAccountAdmin     Role = "ACCOUNT_ADMIN"
	RoleService          Role = "SERVICE"
	RoleAccountAuditor   Role = "ACCOUNT_AUDITOR"
)

func (e Role) ToPointer() *Role {
	return &e
}

func (e *Role) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "LIGHTSPIN_ADMIN":
		fallthrough
	case "CISCO_SUBSCRIBER":
		fallthrough
	case "SELF_PROVISIONING":
		fallthrough
	case "CI_CD_SCANNER":
		fallthrough
	case "PORTSHIFT_ADMIN":
		fallthrough
	case "PORTSHIFT_AUDITOR":
		fallthrough
	case "ACCOUNT_ADMIN":
		fallthrough
	case "SERVICE":
		fallthrough
	case "ACCOUNT_AUDITOR":
		*e = Role(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Role: %v", v)
	}
}
