// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ServerlessVulnerabilitiesWidget struct {
	Bars []SingleBar `json:"bars,omitempty"`
}

func (o *ServerlessVulnerabilitiesWidget) GetBars() []SingleBar {
	if o == nil {
		return nil
	}
	return o.Bars
}
