// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ServerlessAzureInstallationDetails struct {
	AccessKey        *string `json:"accessKey,omitempty"`
	SecretAccessKey  *string `json:"secretAccessKey,omitempty"`
	ServiceAccountID *string `json:"serviceAccountId,omitempty"`
	TemplateURL      *string `json:"templateUrl,omitempty"`
}

func (o *ServerlessAzureInstallationDetails) GetAccessKey() *string {
	if o == nil {
		return nil
	}
	return o.AccessKey
}

func (o *ServerlessAzureInstallationDetails) GetSecretAccessKey() *string {
	if o == nil {
		return nil
	}
	return o.SecretAccessKey
}

func (o *ServerlessAzureInstallationDetails) GetServiceAccountID() *string {
	if o == nil {
		return nil
	}
	return o.ServiceAccountID
}

func (o *ServerlessAzureInstallationDetails) GetTemplateURL() *string {
	if o == nil {
		return nil
	}
	return o.TemplateURL
}
