// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TopRiskyServerlessFunction struct {
	Name *string                      `json:"name,omitempty"`
	Risk *ServerlessFunctionRiskLevel `json:"risk,omitempty"`
}

func (o *TopRiskyServerlessFunction) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TopRiskyServerlessFunction) GetRisk() *ServerlessFunctionRiskLevel {
	if o == nil {
		return nil
	}
	return o.Risk
}
