// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TraceAnalysisStatus string

const (
	TraceAnalysisStatusInProgress TraceAnalysisStatus = "IN_PROGRESS"
	TraceAnalysisStatusReady      TraceAnalysisStatus = "READY"
)

func (e TraceAnalysisStatus) ToPointer() *TraceAnalysisStatus {
	return &e
}

func (e *TraceAnalysisStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "IN_PROGRESS":
		fallthrough
	case "READY":
		*e = TraceAnalysisStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TraceAnalysisStatus: %v", v)
	}
}
