// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TrustedSignerCloudAccountInput struct {
	ID         *string                         `json:"id,omitempty"`
	Status     *TrustedSignerClusterStatus     `json:"status,omitempty"`
	Validation *TrustedSignerClusterValidation `json:"validation,omitempty"`
}

func (o *TrustedSignerCloudAccountInput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TrustedSignerCloudAccountInput) GetStatus() *TrustedSignerClusterStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *TrustedSignerCloudAccountInput) GetValidation() *TrustedSignerClusterValidation {
	if o == nil {
		return nil
	}
	return o.Validation
}
