// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type UnidentifiedPodsRuleAction string

const (
	UnidentifiedPodsRuleActionDetect UnidentifiedPodsRuleAction = "DETECT"
	UnidentifiedPodsRuleActionBlock  UnidentifiedPodsRuleAction = "BLOCK"
)

func (e UnidentifiedPodsRuleAction) ToPointer() *UnidentifiedPodsRuleAction {
	return &e
}

func (e *UnidentifiedPodsRuleAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DETECT":
		fallthrough
	case "BLOCK":
		*e = UnidentifiedPodsRuleAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UnidentifiedPodsRuleAction: %v", v)
	}
}
