// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WorkloadVulnerabilitiesWidget struct {
	Bars                  []SingleBar `json:"bars,omitempty"`
	TotalVulnerableImages *int64      `json:"totalVulnerableImages,omitempty"`
	TotalVulnerablePods   *int64      `json:"totalVulnerablePods,omitempty"`
}

func (o *WorkloadVulnerabilitiesWidget) GetBars() []SingleBar {
	if o == nil {
		return nil
	}
	return o.Bars
}

func (o *WorkloadVulnerabilitiesWidget) GetTotalVulnerableImages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalVulnerableImages
}

func (o *WorkloadVulnerabilitiesWidget) GetTotalVulnerablePods() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalVulnerablePods
}
